# Generated by Django 4.2 on 2023-04-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='study_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.studycategory'),
            preserve_default=False,
        ),
    ]
