# Generated by Django 4.2 on 2023-04-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_studycategory_program_study_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='study_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.studycategory'),
        ),
    ]
