# Generated by Django 4.1.7 on 2023-04-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_setting_hero_title_alter_program_study_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='study_level',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.studycategory'),
        ),
    ]
