# Generated by Django 4.1.7 on 2023-04-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_setting_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
