# Generated by Django 4.1.7 on 2023-04-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_program_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('-name',), 'verbose_name_plural': 'programs'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('-name',), 'verbose_name_plural': 'testimonials'},
        ),
    ]
