# Generated by Django 4.1.7 on 2023-04-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_program_options_alter_testimonial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studycategory',
            options={'verbose_name_plural': 'studyCategories'},
        ),
    ]
