# Generated by Django 4.1.7 on 2023-04-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_lecture_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ('-name',), 'verbose_name_plural': 'lectures'},
        ),
        migrations.AddField(
            model_name='program',
            name='lectures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.lecture'),
        ),
    ]
