# Generated by Django 4.1.7 on 2023-04-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_lecture_options_program_lectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(upload_to='lectures/'),
        ),
    ]
